import torch
import numpy as np
from gym import Space
from typing import Tuple
from ..util import MemoryBuffer
import random

if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
    print("Working with GPU")
else:
    DEVICE = torch.device('cpu')
    print("Working with CPU")


class DoubleDQNAgent(object):
    """
    Reinforcement learning agent using Double DQN to learn
    """

    def __init__(self, main_network: torch.nn.Module, target_network: torch.nn.Module, memory: MemoryBuffer,
                 epsilon_info: Tuple[float, float, float], gamma: float, tau: float, action_space: Space) -> None:

        """
        Parameters
            `main_network`: network used for Q value estimation
            `target_network`: network used to calculate Target Q
            `memory`: buffer used to store experience/transitions
            `epsilon_info`: tuple containing the epsilon max, min, decay.
                Formatted as `(EPSILON_MAX, EPSILON_MIN, EPSILON_DECAY)`
            `gamma`: discount rate
            `tau`: polyak averaging constant for parameter copying
            `action_space`: the action space of the environment
        """
        self.memory = memory
        self.q_net = main_network
        self.q_net_prime = target_network

        self.action_space = action_space

        self.epsilon, self.min_epsilon, self.epsilon_decay = epsilon_info
        self.gamma = gamma
        self.tau = tau

    def choose_action(self, state):
        """
        Use epsilon greedy policy to select the next action

        Parameters
            `state`: observation to be used to decide the next action

        Returns
            `action`: see the action_space to determine type
        """

        # With probability Epsilon, select a random action
        if random.random() < self.epsilon:
            return self.action_space.sample()

        # Generate Expected Future Return
        state_tensor = torch.tensor(state)
        q_values = self.q_net.forward(state_tensor)

        # Select the action with the best estimated future return
        return torch.argmax(q_values).item()

    def learn(self, batch_size):
        """
        Initiates experience replay

        Parameters:
            `batch_size`: the size of the batch to be sampled
        """

        # Being the learning process when the number of experiences in the buffer is greater than the batch sized
        # desired
        if len(self.memory.buffer) < batch_size:
            return

        states, actions, rewards, next_states, dones = self.memory.sample(batch_size)

        # Convert into tensor
        states = torch.FloatTensor(np.asarray(states))
        actions = torch.LongTensor(np.asarray(actions))
        rewards = torch.FloatTensor(rewards)
        next_states = torch.FloatTensor(np.asarray(next_states))
        dones = torch.LongTensor(dones)

        q_values = self.q_net(states)
        next_q_values_prime = self.q_net_prime(next_states)

        '''
        Selected using the Q values generated by the main network (Q)
        Returns a 1D tensor of the q values reflecting the actions that the agent took at that state in the past
        '''
        q_values_of_actions_taken = q_values[torch.arange(q_values.size(0)), actions]

        '''
        Select the best action to take, given the q values generated by the target network (Q')
        Returns a 1D tensor of the best action to take given the state
        '''
        actions_prime = torch.argmax(next_q_values_prime, dim=1)

        next_q_values = self.q_net(next_states)
        '''
        Using the actions_prime generated by the target network, select the q values of taking action prime (a') 
        generated using the target network, given the state
        Returns a 1D Tensor of q values generated using the main network (Q) at time T + 1 given action prime (a')
        '''
        next_q_values_of_actions_taken = next_q_values[torch.arange(next_q_values.size(0)), actions_prime]

        q_target = rewards + self.gamma * (1 - dones) * next_q_values_of_actions_taken

        loss = self.q_net.loss(q_values_of_actions_taken, q_target)
        self.q_net.optimizer.zero_grad()
        loss.backward()
        self.q_net.optimizer.step()

        self.epsilon *= self.epsilon_decay
        self.epsilon = max(self.epsilon, self.min_epsilon)

        for target_param, param in zip(self.q_net_prime.parameters(), self.q_net.parameters()):
            target_param.data.copy_(self.tau * param + (1 - self.tau) * target_param)

